apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejm-accountbalancenm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ejm-accountbalancenm
  template:
    metadata:
      labels:
        app: ejm-accountbalancenm
    spec:
      containers:
        - name: ejm-container
          image: ejmacr.azurecr.io/ejmapiaccountbalancenmfunctionservice:v1
          ports:
            - containerPort: 8512
          env:
            - name: FUNCTIONS_WORKER_RUNTIME
              value: "dotnet"
            - name: ConnectionStrings
              value: "server=tcp:sql-svr-dev-ejm-001.database.windows.net,1433;Initial Catalog=sql-db-dev-ejm-001;Persist Security Info=False;User ID=readonlyazure;Password=Extract1!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
            - name: TIME_OUT
              value: "180" 
      imagePullSecrets:
        - name: myregistry-creds
---
apiVersion: v1
kind: Service
metadata:
  name: ejm-accountbalancenm-service
spec:
  selector:
    app: ejm-accountbalancenm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # type: LoadBalancer
  # externalTrafficPolicy: Local