name: Build and Deploy Prod Function App

on:
  push:
    branches:
      - main
    paths:
      - 'GenerateJWT/**'
  repository_dispatch:
    types: [deploy-generate-jwt]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'FAP-HUB-AUTOMATION-001'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'GenerateJWT'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '18.x'   


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PRODFUNCTIONAPP_PUBLISH_PROFILE }}
