FROM mcr.microsoft.com/azure-functions/dotnet:4 AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["./JM.eJM.API.NM.Functions/JM.eJM.API.NM.Functions.csproj", "JM.eJM.API.NM.Functions/"]
COPY ["./JM.eJM.API.NM.Functions/local.settings.json", "JM.eJM.API.NM.Functions/"]
COPY ["./JM.eJM.API.NM.DTO/JM.eJM.API.NM.DTO.csproj", "JM.eJM.API.NM.DTO/"]
COPY ["./JM.eJM.API.NM.Services/JM.eJM.API.NM.Services.csproj", "JM.eJM.API.NM.Services/"]
COPY ["./JM.eJM.API.NM.Functions.UnitTests", "JM.eJM.API.NM.Functions.UnitTests/"]
RUN dotnet restore "JM.eJM.API.NM.Functions/JM.eJM.API.NM.Functions.csproj"
COPY . .
WORKDIR "/src/JM.eJM.API.NM.Functions"
RUN dotnet build "JM.eJM.API.NM.Functions.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "JM.eJM.API.NM.Functions.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true